<!-- <div class="row">
 <div class="about col-xs-4">
 	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF	ABOUT ME STUFF
 </div>
 <div class="content-box col-md-4 line">
		<?php 
			// require_once (__DIR__ . "/../controler/read-posts.php");
 		?>
 </div>
</div> -->
